# Generated by Django 4.0.4 on 2022-05-16 10:59

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Eメールアドレス')),
                ('nickname', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=20, unique=True, verbose_name='URLスラッグ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/characters/', verbose_name='キャラクター画像')),
                ('name', models.CharField(max_length=50, verbose_name='キャラクター名')),
                ('world', models.CharField(max_length=20, verbose_name='所属ワールド')),
                ('how_to_get', models.CharField(choices=[('happiness', 'ハピネスBOX'), ('premium', 'プレミアムBOX')], default='premium', max_length=20, verbose_name='獲得方法')),
                ('description', models.CharField(max_length=100, verbose_name='説明文')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'キャラクター',
                'verbose_name_plural': 'キャラクター',
                'db_table': 'character',
                'ordering': ['created_at'],
            },
        ),
    ]
