# Generated by Django 4.0.4 on 2022-05-16 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
