# Generated by Django 4.0.4 on 2022-05-16 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['created_at'], 'verbose_name': 'ユーザ', 'verbose_name_plural': 'ユーザ'},
        ),
    ]
