# Generated by Django 4.0.4 on 2022-05-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_character_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='how_to_get',
            field=models.CharField(choices=[('happiness', 'ハピネスBOX'), ('premium', 'プレミアムBOX')], default='premium', max_length=20, verbose_name='獲得方法'),
        ),
    ]
